### PR TITLE
Add reload functionality

### PR DESCRIPTION
**Pull request by stephane-ly**

### CODE REVIEW

**Comment by wichtounet** [comment]
Can you please fix the conflicts first ? use git pull, then resolve the conflicts and commit and push again.

**Comment by wichtounet** [comment]
It is probably related to 0baa4d3b77f2ad4af6a09d3944818a07d9364cca where I renamed the buttons.

**Comment by stephane-ly** [comment]
There should be no conflicts now.

**Comment by wichtounet** [comment]
Yes, but the code did not compile. You let the conflict markers in the code.

**Pull request merged**
